def main():
    print("Bombers:")
    print("CF Bugs Yamaguchi")
    print("2B Blaze Winterbottom")
    print("3B Dieter Gomez")
    print("C Buzz Norton")
    print("RF Buddy Lamont")
    print("1B Manny Del Greco")
    print("LF Joe Bill Silver")
    print("SS Tiny Howl")
    print("P Scooter McKeever")
    print("\nLoons:")
    print("LF Gloveless Joe Topanga")
    print("2B Nate Colbert")
    print("CF Franklin Vega")
    print("1B JP Primero")
    print("3B Billy De Jesus")
    print("RF Lamont Bradleys")
    print("C Jose Sunderland")
    print("SS Ford Stipe")
    print("P Butch Flores")

if __name__ == '__main__':
    main()
