"""Game facts the hosts say that a feed can record, and how they are narrated.

Batted-ball depth, lane and hardness; runners who score or take third; the
runs a hit or home run drove in; a starter's season record; pinch hitters.
Each is recorded in the fixture (never as transcript text), narrated only
when recorded, and generated by the simulator where its field model knows it.
"""
import copy
import json
from pathlib import Path
import re
import unittest

import fieldsim
from annotate_transcript_facts import facts_from_words, season_pitching
from renderers import NarrativeRenderer
from renderers.narrative.batted_ball import gate_templates, spot_direction, supported_claims, template_claims
from transcript_game_fixtures import LEDGER_DIR, OUTPUT_DIR, SOURCE_DIR, compile_game


def episode(number):
    return json.loads((OUTPUT_DIR / f'episode_{number:03d}.json').read_text())


def ledger(number):
    return json.loads((LEDGER_DIR / f'episode_{number:03d}.json').read_text())


class SayEverything(NarrativeRenderer):
    """Every optional sentence said, so a test sees what a fact enables."""

    def _optional(self, name):
        super()._optional(name)
        return True


def play_text(renderer, text, index):
    lines = text.splitlines()
    low, high = renderer._play_line_map[index]
    return '\n'.join(line for line in lines[low:high] if not line.startswith('[TTS'))


def call_of(text):
    """The words after the last delivery cue: the ball in play's call."""
    return text.rsplit('...', 1)[-1]


class TestBattedBallClaims(unittest.TestCase):
    def test_claims_need_their_fact(self):
        self.assertEqual(template_claims('Ripped into the gap, and that will roll all the way to the wall.'),
                         {'hard', 'gap', 'wall'})
        wall = supported_claims({'depth': 'wall', 'lane': 'left_line'}, 'Double')
        self.assertTrue({'deep', 'wall', 'corner', 'line'} <= wall)
        self.assertNotIn('gap', wall)
        self.assertEqual(supported_claims({'trajectory': 'fly_ball'}, 'Single'), set())
        self.assertIn('wall', supported_claims({}, 'Home Run'))
        self.assertIn('soft', supported_claims({'categoryOverride': 'bloop'}, 'Single'))
        self.assertIn('ground_path', supported_claims({'trajectory': 'ground_ball'}, 'Single'))
        templates = ['Lined {direction}. That one drops in.', 'Hard liner {direction}.', 'Lined into shallow {direction_noun}.']
        self.assertEqual(gate_templates(templates, set()), templates[:1])
        self.assertEqual(gate_templates(templates, {'hard'}), templates[:2])

    def test_directions_follow_depth_and_lane(self):
        self.assertEqual(spot_direction({'lane': 'left_line', 'trajectory': 'line_drive'}, 'Double', 'to left field', 'left field'),
                         ('down the left field line', 'left field'))
        self.assertEqual(spot_direction({'lane': 'right_line', 'trajectory': 'ground_ball'}, 'Single', 'to first', 'first'),
                         ('down the first base line', 'right field'))
        self.assertEqual(spot_direction({'lane': 'right_center', 'depth': 'deep'}, 'Flyout', 'to center field', 'center field'),
                         ('to deep right center', 'right center'))
        self.assertEqual(spot_direction({'depth': 'shallow', 'trajectory': 'fly_ball'}, 'Single', 'to left field', 'left field'),
                         ('into shallow left', 'left'))
        self.assertEqual(spot_direction({'lane': 'middle', 'trajectory': 'ground_ball'}, 'Single', 'to second', 'second'),
                         ('up the middle', 'center field'))
        self.assertEqual(spot_direction({}, 'Single', 'to left field', 'left field'), ('to left field', 'left field'))

    def test_strict_broadcasts_claim_no_unrecorded_wall_track_or_hard_contact(self):
        """Over all 17 fitted broadcasts, a wall, warning track or hard hit is
        said about a ball only when its facts record it."""
        checked = 0
        for path in sorted(OUTPUT_DIR.glob('episode_*.json')):
            data = json.loads(path.read_text())
            renderer = NarrativeRenderer(data)
            text = renderer.render()
            for index, play in enumerate(data['liveData']['plays']['allPlays']):
                hit = next((event.get('hitData', {}) for event in play['playEvents']
                            if event.get('details', {}).get('code') == 'X'), None)
                if hit is None or play['result']['event'] == 'Home Run':
                    continue
                call = call_of(play_text(renderer, text, index))
                supported = supported_claims(hit, play['result']['event'])
                with self.subTest(episode=path.stem, play=index):
                    if 'wall' not in supported:
                        self.assertNotRegex(call, r'\bwall\b')
                    if 'warning_track' not in supported:
                        self.assertNotIn('warning track', call)
                    if 'hard' not in supported:
                        self.assertNotRegex(call, r'\bHard grounder\b|\bHammered\b')
                    checked += 1
        self.assertGreater(checked, 600)

    def test_recorded_facts_are_narrated(self):
        renderer = NarrativeRenderer(episode(49))
        text = renderer.render()
        plays = episode(49)['liveData']['plays']['allPlays']
        ground_rule = next(i for i, play in enumerate(plays)
                           if any(e.get('hitData', {}).get('categoryOverride') == 'ground_rule' for e in play['playEvents']))
        self.assertIn('ground-rule double', play_text(renderer, text, ground_rule))
        track = [i for i, play in enumerate(plays) if play['result']['event'] == 'Flyout'
                 and any(e.get('hitData', {}).get('depth') == 'warning_track' for e in play['playEvents'])]
        self.assertTrue(track)
        self.assertTrue(any('warning track' in play_text(renderer, text, i) for i in track))


class TestRealFeedSpots(unittest.TestCase):
    """Real StatsAPI balls carry coordinates and distance, not depth/lane."""

    def test_depth_and_lane_derived_from_coordinates_like_the_simulator(self):
        from renderers.narrative.batted_ball import with_derived_spot
        # A real feed's warning-track catch in left center and a grounder up the middle.
        caught = {'launchSpeed': 103.6, 'launchAngle': 32, 'totalDistance': 365, 'trajectory': 'fly_ball',
                  'hardness': 'hard', 'location': '8', 'coordinates': {'coordX': 82.0, 'coordY': 57.0}}
        derived = with_derived_spot(caught, 'Flyout')
        self.assertEqual((derived['depth'], derived['lane']), ('warning_track', 'left_center'))
        dx, dy = (82.0 - 125.42) * 2.495, (198.27 - 57.0) * 2.495
        import math
        self.assertEqual({k: derived[k] for k in ('depth', 'lane')},
                         fieldsim.spot_facts(math.degrees(math.atan2(dx, dy)), 365, 'fly_ball', 'Flyout', True,
                                             math.hypot(dx, dy)))
        grounder = {'trajectory': 'ground_ball', 'hardness': 'hard', 'totalDistance': 6,
                    'coordinates': {'coordX': 126.0, 'coordY': 140.0}}
        self.assertEqual(with_derived_spot(grounder, 'Single')['lane'], 'middle')
        # Explicit fields win, including the simulator's "nothing notable".
        self.assertEqual(with_derived_spot({**caught, 'depth': None, 'lane': None}, 'Flyout')['depth'], None)
        self.assertEqual(with_derived_spot({**caught, 'depth': 'shallow'}, 'Flyout')['depth'], 'shallow')
        self.assertNotIn('depth', with_derived_spot({'trajectory': 'fly_ball'}, 'Flyout'))

    def test_anonymized_real_feed_keeps_location_phrasing(self):
        from blind_judge import real_game, render
        data = real_game('real_gameday.json', 7)
        hits = [event['hitData'] for play in data['liveData']['plays']['allPlays']
                for event in play['playEvents'] if 'hitData' in event]
        self.assertTrue(all('coordinates' in hit for hit in hits if hit.get('trajectory')))
        calls = [line.rsplit('...', 1)[-1] for line in render(data, 7).splitlines() if '...' in line]
        spots = [call for call in calls if 'foul' not in call and re.search(
            r'\b(?:gap|left center|right center|line|corner|wall|warning track|deep|shallow|up the middle)\b', call)]
        self.assertGreaterEqual(len(spots), 15)


class TestRunnersAndRuns(unittest.TestCase):
    def test_each_runner_who_scores_is_named(self):
        data = episode(13)
        renderer = SayEverything(data)
        text = renderer.render()
        index = next(i for i, play in enumerate(data['liveData']['plays']['allPlays'])
                     if play['result']['event'] == 'Triple' and play['result'].get('rbi') == 3)
        call = play_text(renderer, text, index)
        for name in ('Nomo', 'Brown', 'Sessions'):
            self.assertRegex(call, rf'{name}[^.]*\b(?:score|scores|scoring)\b')
        self.assertIn('three-run triple', call)

    def test_home_run_says_its_runs(self):
        data = episode(49)
        renderer = SayEverything(data)
        text = renderer.render()
        for index, play in enumerate(data['liveData']['plays']['allPlays']):
            if play['result']['event'] == 'Home Run' and not play['result'].get('isWalkoff'):
                words = {1: 'solo', 2: 'two-run', 3: 'three-run'}[play['result']['rbi']]
                self.assertIn(words, play_text(renderer, text, index))

    def test_runner_sentences_need_recorded_movements(self):
        data = episode(13)
        for play in data['liveData']['plays']['allPlays']:
            play['runners'] = [runner for runner in play['runners']
                               if runner['details']['runner']['id'] == play['matchup']['batter']['id']]
        text = SayEverything(data).render()
        self.assertNotRegex(text, r'\b(?:Nomo|Brown) will score\b')


class TestSeasonStatistics(unittest.TestCase):
    def test_compiled_into_boxscore_season_stats_and_said_in_the_lineup(self):
        data = episode(49)
        players = data['liveData']['boxscore']['teams']['away']['players']
        shemper = next(entry for entry in players.values() if entry['person']['fullName'] == 'Brocktune Shemper')
        self.assertEqual(shemper['seasonStats']['pitching'], {'wins': 7, 'losses': 8, 'era': '5.21'})
        pregame = NarrativeRenderer(data).render().split('[TTS', 1)[0]
        self.assertRegex(pregame, r'record of (?:7|seven) and (?:8|eight)')
        self.assertIn('5.21', pregame)

    def test_unknown_players_are_rejected(self):
        record = ledger(49)
        record['game']['season_stats'] = {'Nobody Here': {'pitching': {'era': '1.00'}}}
        with self.assertRaises(ValueError):
            compile_game(record, (SOURCE_DIR / record['source_file']).read_bytes())

    def test_no_record_without_season_stats(self):
        data = episode(49)
        for team in data['liveData']['boxscore']['teams'].values():
            team.pop('players', None)
        self.assertNotIn('record of', NarrativeRenderer(data).render())

    def test_annotation_reads_the_hosts_record(self):
        lines = ['And batting ninth, right handed starting pitcher, Brocktune Shemper.',
                 "He enters tonight's contest with a record of seven and eight with a 5.21 ERA."]
        self.assertEqual(season_pitching(lines, ['Brocktune Shemper', 'Zach Valentine']),
                         {'Brocktune Shemper': {'wins': 7, 'losses': 8, 'era': '5.21'}})


class TestPinchHitters(unittest.TestCase):
    def test_compiled_as_an_offensive_substitution_and_said_in_the_intro(self):
        data = episode(49)
        plays = data['liveData']['plays']['allPlays']
        index = next(i for i, play in enumerate(plays) if play['matchup']['batter']['fullName'] == 'Royce Babcock')
        action = plays[index]['playEvents'][0]
        self.assertEqual(action['details']['eventType'], 'offensive_substitution')
        self.assertTrue(action['isSubstitution'])
        self.assertEqual(data['gameData']['players'][f"ID{action['replacedPlayer']['id']}"]['fullName'], 'Brocktune Shemper')
        renderer = NarrativeRenderer(data)
        text = play_text(renderer, renderer.render(), index)
        self.assertRegex(text, r'pinch[- ]hit')
        self.assertNotIn('Offensive Substitution', text)
        lines = renderer.render().splitlines()
        low, high = renderer._play_line_map[index]
        markers = [line for line in lines[low:high] if line.startswith('[TTS')]
        self.assertEqual(markers[:2], ['[TTS SPLIT HERE DELAY:11.5s]', '[TTS SPLIT HERE DELAY:9.5s]'])

    def test_replaced_man_and_slot_only_when_recorded(self):
        record = ledger(49)
        play = next(play for play in record['plays'] if play['batter'] == 'Royce Babcock')
        play['substitution'] = {'type': 'pinch_hitter'}
        data = compile_game(record, (SOURCE_DIR / record['source_file']).read_bytes())
        for draw in range(6):
            for item in data['liveData']['plays']['allPlays']:
                if item['matchup']['batter']['fullName'] == 'Royce Babcock':
                    item.setdefault('commentaryRng', {})['play_start'] = {'flow': [draw] * 12}
            text = NarrativeRenderer(copy.deepcopy(data)).render()
            intro = next(line for line in text.splitlines() if 'Babcock' in line and 'pinch' in line)
            self.assertNotIn('Shemper', intro)
            self.assertNotIn('spot', intro)


class TestPinchHitterSituation(unittest.TestCase):
    def test_bases_empty_intro_can_say_the_outs(self):
        data = episode(35)
        plays = data['liveData']['plays']['allPlays']
        index = next(i for i, play in enumerate(plays) if play['matchup']['batter']['fullName'] == 'Benny Standingbear')
        intros = set()
        for draw in range(20):
            plays[index]['commentaryRng'] = {'play_start': {'flow': [draw] * 12}}
            renderer = NarrativeRenderer(copy.deepcopy(data))
            intros.add(play_text(renderer, renderer.render(), index).splitlines()[0])
        joined = ' '.join(intros)
        self.assertIn('Bases empty, and two outs now for Benny Standingbear, who will pinch-hit for Frank Gibson.', joined)


class TestStrikeoutNames(unittest.TestCase):
    def test_feed_strikeout_names_end_their_call(self):
        for number in (1, 3):
            data = json.loads(Path(f'test_fixture_pbp_example_{number}.json').read_text())
            text = NarrativeRenderer(data).render()
            self.assertNotRegex(text, r'(?m)(?:strike three|called a strike),$')


class TestSimulatorFacts(unittest.TestCase):
    def ball(self, **kwargs):
        values = dict(outcome='Double', fielder='LF', trajectory='line_drive', location='LF', spray=-40.0,
                      landing=(0, 0), distance=300.0, release_point=fieldsim.polar(fieldsim.fence_distance(-40.0) - 2, -40.0))
        values.update(kwargs)
        return fieldsim.BattedBall(**values)

    def test_spot_from_the_field_model(self):
        self.assertEqual(fieldsim.spot(self.ball()), {'depth': 'wall', 'lane': 'left_line'})
        caught = self.ball(outcome='Flyout', caught=True, spray=12.0, distance=fieldsim.fence_distance(12.0) - 10,
                           trajectory='fly_ball', release_point=None)
        self.assertEqual(fieldsim.spot(caught), {'depth': 'warning_track', 'lane': 'right_center'})
        bloop = self.ball(outcome='Single', spray=3.0, distance=180.0, release_point=fieldsim.polar(190.0, 3.0))
        self.assertEqual(fieldsim.spot(bloop), {'depth': 'shallow'})
        grounder = self.ball(outcome='Single', trajectory='ground_ball', spray=2.0, distance=150.0)
        self.assertEqual(fieldsim.spot(grounder), {'lane': 'middle'})
        self.assertEqual(fieldsim.hardness(101.0), 'hard')
        self.assertEqual(fieldsim.hardness(70.0), 'soft')

    def test_simulated_balls_in_play_carry_the_facts(self):
        from baseball import BaseballSimulator
        from example_games import EXAMPLE_GAMES
        game = EXAMPLE_GAMES[0]
        simulator = BaseballSimulator(game.team1, game.team2, game_seed=game.game_seed)
        simulator.play_game()
        hits = [event['hitData'] for play in simulator.gameday_data['liveData']['plays']['allPlays']
                for event in play['playEvents'] if 'hitData' in event and 'launchSpeed' in event['hitData']]
        self.assertTrue(hits)
        self.assertTrue(all(hit['hardness'] in ('soft', 'medium', 'hard') for hit in hits))
        self.assertTrue(any(hit.get('depth') for hit in hits))
        self.assertTrue(any(hit.get('lane') for hit in hits))


class TestAnnotation(unittest.TestCase):
    def test_words_to_facts(self):
        self.assertEqual(facts_from_words('Hard grounder up the middle, and that one gets through.', 'Single', 'CF', 'ground_ball'),
                         {'lane': 'middle', 'hardness': 'hard'})
        self.assertEqual(facts_from_words('Hit in the air to deep right center. And he makes the catch on the warning track.',
                                          'Flyout', 'CF', 'fly_ball'),
                         {'depth': 'warning_track', 'lane': 'right_center'})
        self.assertEqual(facts_from_words('Looper into shallow left, and that one falls into the gap.', 'Single', 'LF', 'fly_ball'),
                         {'depth': 'shallow', 'lane': 'left_center', 'hardness': 'soft'})
        # "Over the wall" is not where the ball came to rest.
        self.assertEqual(facts_from_words('Driven down the left field line. It will bounce over the wall.', 'Double', 'LF', 'line_drive'),
                         {'lane': 'left_line'})
        # Shallow and deep together are contradictory: nothing is recorded.
        self.assertNotIn('depth', facts_from_words('Shallow center, no, deep center.', 'Flyout', 'CF', 'fly_ball'))
        self.assertEqual(facts_from_words('A ground-rule double.', 'Double', 'LF', 'line_drive')['categoryOverride'], 'ground_rule')

    def test_ledgers_and_references_record_the_facts(self):
        counts = {'depth': 0, 'lane': 0, 'hardness': 0}
        for path in LEDGER_DIR.glob('episode_*.json'):
            for play in json.loads(path.read_text())['plays']:
                for key in counts:
                    counts[key] += key in play.get('hit', {})
        self.assertGreater(counts['depth'], 150)
        self.assertGreater(counts['lane'], 100)
        self.assertGreater(counts['hardness'], 120)
        substitutions = sum('substitution' in play for path in LEDGER_DIR.glob('episode_*.json')
                            for play in json.loads(path.read_text())['plays'])
        self.assertEqual(substitutions, 26)
        stats = sum(len(json.loads(path.read_text())['game'].get('season_stats', {}))
                    for path in LEDGER_DIR.glob('episode_*.json'))
        self.assertEqual(stats, 26)


if __name__ == '__main__':
    unittest.main()
